---
title: "Bianca Muniz's CV"
author: Bianca Muniz
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/18s6-s3Rfee62fEGagd0JziyXlnQHXGzq-KRmsJxMhfM/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```

```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```

# Aside

```{r}
if(params$pdf_mode){
  cat("Veja este CV online em biamuniz.github.io/resume/")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/biamuniz/resume/raw/master/bmuniz_cv.pdf)")
}
```

## Contato {#contact}

```{r}
CV %>% print_contact_info()
```

## Idiomas {#skills}

```{r}
CV %>% print_skill_bars()
```


## Hard skills {#hard}

```{r}
CV %>% print_hard_bars()
```

## Soft skills {#soft}

```{r}
CV %>% print_soft_bars()
```



# Main

## Bianca Muniz {#title}

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```

## Experiência Profissional {data-icon="suitcase"}

```{r}
CV %<>% print_section('work')
```

## Formação Acadêmica {data-icon="graduation-cap"}

```{r}
CV %<>% print_section('education')
```

<!-- These breaks just force a new page so section doesnt get cut off -->

## Experiências complementares {data-icon="presentation"}

```{r}
CV %<>% print_section('talks')
```

## Disclaimer {#disclaimer}

Feito com o pacote em R <br>
[**pagedown**](https://github.com/rstudio/pagedown).



Última atualização `r Sys.Date()`.

